# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image:
  file: .gitpod.Dockerfile

# Command to start on workspace startup (optional)
#tasks:
#  - init: 'echo "TODO: Replace with init/build command"'
#    command: 'echo "TODO: Replace with command to start project"'
